[tool.bumpversion]
current_version = "2.7.1"
commit = false
# https://graphite.dev/guides/git-commit--no-verify#when-to-use-object-object
commit_args = "--no-verify --author='Automated-Commit-Though-Bumper <shivkj001@gmail.com>'"
tag = false
tag_name = "v{new_version}"
allow_dirty = true

message = "Version updated from {current_version} to {new_version}"

[[tool.bumpversion.files]]
filename = "src/streamAPI/__init__.py"
